### ISSUE TITLE
Add proper licensing

### ISSUE THREAD

**Issue by cdgriffith** [drathier/stack-overflow-import#6]
"The PSF license was developed specifically and only for Python and its standard libraries. If you want to license your code for contribution to the PSF, do not use the PSF license; "

https://wiki.python.org/moin/PythonSoftwareFoundationLicenseFaq

I would suggest MIT, BSD, or maybe in this case WTFPL. Basically just add a permissive license file and mention of it in readme you're good to go.

**Comment by pombredanne** [comment]
You mention in your README `This module is WTFPL-licensed as I blatantly copied multiple lines of code from the Python standard library.` therefore you cannot just relicense PSF-licensed under WTPL. That part should stay under the PSF.

**Comment by drathier** [comment]
There. Solved it.
